config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get '/home/about', to: 'homes#about'
  devise_for :users
  resources :users, only: [:show, :edit, :update, :index]
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, uniqueness: true, presence: true, length: { in: 2..20 }
  validates :introduction, length: {maximum: 50}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
       redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @users = User.all
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user.id)
    end
    
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
	      <th>name</th>
	      <th><%= user.name %></th>
      </tr>
      <tr>
	      <th>introduction</th>
	      <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>

  <div class="row">
      <%= link_to "", edit_user_path(user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
  </div>

  <h2 class="mt-3">New book</h2>
  <%= form_with model: book, local:true do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class: "form-control book_title" %>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class: "form-control book_body" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class: "btn btn-success" %>
  </div>
  <% end %>

app/views/books/edit.html.erb
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

  		<h1>Editing Book</h1>
  		
  		<% @book.errors.full_messages.each do |msg| %>
        <div class="error_explaination">
          <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
          <ul>
           <li><%= msg %></li>
          </ul>
        </div>
      <% end %>
      
     	<%= form_with model:@book, local: true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book', class: 'btn btn-success' %>
        </div>
      <% end %>

  		<%= link_to 'Show', book_path(@book.id) %>|
  		<%= link_to 'Back', books_path %>

      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
  <% @book.errors.full_messages.each do |msg| %>
    <div class="error_explaination">
      <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
      <ul>
        <li><%= msg %></li>
      </ul>
    </div>
  <% end %>

<div class="container px-5 px-sm-0">
  <div class="row">

    <div class="col-md-3">
      <%= render 'books/list', user:@user, book:@book %>
    </div>

    <div class="col-md-8 offset-md-1">

      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                <div class="user-profile-image"><%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60" %></div>
                <% end %>
              </td>
              <td class="book-title"><%= link_to book.title, book_path(book.id) %></td>
              <td class="book-body"><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(book), class: "fa fa-heart heart-after", method: :delete do %>
                      <%= book.favorites.count %>
                    <% end %>
                  </p>
                  <% else %>
                  <p>
                    <%= link_to book_favorites_path(book), class: "far fa-heart", method: :post do %>
                      <%= book.favorites.count %>
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td class="comments">コメント数：<%= book.book_comments.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/books/show.html.erb
<main>
<div class="container px-5 px-sm-0">
  <div class="row">

    <div class="col-md-3">
      <% if @book.user == current_user %>
      <%= render 'books/list', user:current_user, book:Book.new %>
      <% else %>
      <%= render 'books/list', user:@user, book:Book.new %>
      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">

      <h2>Book detail</h2>
      <table class="table">
        <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user.id) do %>
                  <div class="user-profile-image"><%= attachment_image_tag @book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60" %></div>
                  <%= @book.user.name %>
                <% end %>
              </td>
              <td class="book-title"><%= link_to @book.title, book_path(@book.id) %></td>
              <td class="book-body"><%= @book.body %></td>
              <% if @book.user == current_user %>
                <td><%= link_to "Edit", edit_book_path(@book), class: 'btn btn-sn btn-success' %></td>
                <td><%= link_to "Destroy", book_path(@book), class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: '本当に削除しますか？'} %></td>
              <% end %>
              <td>
                <% if @book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(@book), class: "fa fa-heart heart-after", method: :delete do %>
                      <%= @book.favorites.count %>
                    <% end %>
                  </p>
                  <% else %>
                  <p>
                    <%= link_to book_favorites_path(@book), class: "far fa-heart", method: :post do %>
                      <%= @book.favorites.count %>
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td class="comments">コメント数：<%= @book.book_comments.count %></td>
            </tr>
        </tbody>
      </table>

      <table>
        <tbody>
          <% @book.book_comments.each do |book_comment| %>
          <tr>
            <td>
              <%= link_to user_path(book_comment.user.id) do %>
                <div class="user-profile-image"><%= attachment_image_tag book_comment.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60" %></div>
                <%= book_comment.user.name %>
              <% end %>
            </td>
            <td><%= book_comment.comment %></td>
            <td>
              <% if book_comment.user == current_user %>
              <div class="comment-delete">
                <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), class: 'btn btn-sm btn-danger', method: :delete %>
              </div>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <div class="new-comments">
        <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
          <%= f.text_area :comment, rows:'5' %>
          <%= f.submit "送信" %>
        <% end %>
      </div>
    </div>

  </div>
</div>
</main>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
        <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
    <p class="flash flash-<%= key %>">
      <%= value %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand text-white" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

            <% if user_signed_in? %>

            <li class="nav-item">
              <%= link_to 'Home', user_path(current_user.id), class: 'fas fa-home nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Users', users_path, class: 'fas fa-users nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Books', books_path, class: 'fas fa-book-open nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to "logout", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-white' %>
            </li>


            <% else %>

            <li class="nav-item">
             <%= link_to 'Home', root_path, class: 'fas fa-home nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to 'About', home_about_path, class: 'fas fa-link nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to 'sign up', new_user_registration_path, class: 'fas fa-user-plus nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to "login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-white' %>
            </li>

            <% end %>

            </ul>
          </div>
        </div>
      </nav>
    </header>
    
<%= render 'layouts/flash' %>

<main>
  <p></p>
  <%= yield %>
</main>
    

    

    <footer>
  　　<div class="container mt-5">
  	　　<div class="row">
    	　　<div class="mx-auto">
    		　　<p>CopyRight Infratop.inc</p>
    	　　</div>
    　　　</div>
  　　</div>
　　</footer>

  </body>

</html>

app/views/users/_list.html.erb
  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
	      <th>name</th>
	      <th><%= user.name %></th>
      </tr>
      <tr>
	      <th>introduction</th>
	      <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>

  <div class="row">
      <%= link_to "", edit_user_path(user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
  </div>

  <h2 class="mt-3">New book</h2>
  <%= form_with model: book, local:true do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class: "form-control book_title" %>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class: "form-control book_body" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class: "btn btn-success" %>
  </div>
  <% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

    <h2>User info</h2>

    <% @user.errors.full_messages.each do |message| %>
     <div class="error-message">
      <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
      <ul>
        <li><%= message %></li>
      </ul>
     </div>
    <% end %>


    <%= form_with model:@user, local:true do |f| %>

      <label for="user_name">Name</label>
      <div class="form-group">
        <%= f.text_field :name, autofocus: true, id:"inputName" %>
      </div>

      <label for="user_image">Image</label>
      <div class="form-group">
        <%= f.attachment_field :profile_image %>
      </div>

      <label for="user_introduction">Introduction</label>
      <div class="form-group">
        <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction" %>
      </div>
      <div class="form-group">
        <%= f.submit "Update User", class: 'btn btn-secondary' %>
      </div>
    <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/list', user:@user, book:Book.new %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <div class="user-profile-image"><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60" %></div>
              </td>
              <td class="user-name"><%= user.name %></td>
              <td class="user-link"><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <div class="col-md-3">
      <%= render 'users/list', user:@user, book:@book %>
    </div>

    <div class="col-md-8 offset-md-1">

      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <div class="user-profile-image"><%= link_to attachment_image_tag(book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60"), user_path(book.user.id) %></div>

              </td>
              <td class="book-title"><%= link_to book.title, book_path(book.id) %></td>
              <td class="book-body"><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(book), class: "fa fa-heart heart-after", method: :delete do %>
                      <%= book.favorites.count %>
                    <% end %>
                  </p>
                  <% else %>
                  <p>
                    <%= link_to book_favorites_path(book), class: "far fa-heart", method: :post do %>
                      <%= book.favorites.count %>
                    <% end %>
                  </p>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>